#!/bin/bash
# Install F5-TTS (Russian fork) for Saymo — alternative to XTTS+RVC pipeline.
#
# - Creates ~/F5TTS/.venv with f5-tts package (torch 2.11, transformers 5.x)
# - Downloads Misha24-10/F5-TTS_RUSSIAN checkpoints + vocab
# - Writes a helper to ~/.saymo/f5tts_model.txt recording the model dir
#
# Kept isolated from Saymo's main venv because F5-TTS's torch/transformers
# versions conflict with Coqui TTS and mlx-audio pins.

set -eo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

ok()   { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
fail() { echo -e "${RED}✗${NC} $1"; exit 1; }
step() { echo -e "\n${BLUE}→${NC} $1"; }

F5TTS_DIR="$HOME/F5TTS"
MODEL_DIR="$F5TTS_DIR/models/ru"
HF_REPO="${HF_REPO:-Misha24-10/F5-TTS_RUSSIAN}"
VARIANT="${VARIANT:-F5TTS_v1_Base_v2}"  # v2 = +16 epochs, 100% stress marks, artifact filtering

echo "=== Saymo F5-TTS Installer (Russian fork) ==="
echo ""

[ "$(uname -m)" = "arm64" ] || fail "arm64 only. Open Terminal natively."
ok "Architecture: arm64"

command -v python3 >/dev/null || fail "python3 not found."
ok "Prereqs: python3"

# ── Step 1: venv ──
step "Step 1/3: Python venv at $F5TTS_DIR/.venv"
if [ -d "$F5TTS_DIR/.venv" ]; then
    ok "venv already exists"
else
    mkdir -p "$F5TTS_DIR"
    python3 -m venv "$F5TTS_DIR/.venv"
    ok "Created venv"
fi

PY="$F5TTS_DIR/.venv/bin/python"

# ── Step 2: pip install ──
step "Step 2/3: Install f5-tts package (~2-5 min)"
if "$PY" -c "import f5_tts" 2>/dev/null; then
    ok "f5-tts already installed"
else
    "$PY" -m pip install --upgrade pip >/dev/null
    "$PY" -m pip install f5-tts
    ok "f5-tts installed"
fi

# ── Step 3: download Russian model ──
step "Step 3/3: Download $HF_REPO → $MODEL_DIR (~1-3 GB)"
mkdir -p "$MODEL_DIR"

# Download only the variant we need (not all 4 checkpoints — saves ~9 GB).
"$PY" - <<EOF
from huggingface_hub import snapshot_download
p = snapshot_download(
    repo_id="$HF_REPO",
    allow_patterns=[
        "$VARIANT/*.pt",
        "$VARIANT/*.safetensors",
        "$VARIANT/*.yaml",
        "F5TTS_v1_Base/vocab.txt",
        "README.md",
    ],
    local_dir="$MODEL_DIR",
)
print(f"Downloaded to: {p}")
EOF

# Find the checkpoint .pt file
CKPT=$(find "$MODEL_DIR/$VARIANT" -name "*.pt" -size +50M 2>/dev/null | head -1)
[ -n "$CKPT" ] || fail "Expected .pt file missing under $MODEL_DIR/$VARIANT/"

VOCAB="$MODEL_DIR/F5TTS_v1_Base/vocab.txt"
[ -f "$VOCAB" ] || fail "vocab.txt missing at $VOCAB"

# Write discovered paths for reference
cat > "$HOME/.saymo/f5tts_model.txt" <<EOF
# Saymo F5-TTS model info (generated by scripts/install_f5tts.sh)
ckpt_file: $CKPT
vocab_file: $VOCAB
variant: $VARIANT
hf_repo: $HF_REPO
EOF

ok "Model ready at $CKPT"

echo ""
echo -e "${GREEN}=== Done ===${NC}"
echo ""
echo "To activate in Saymo, add to ~/.saymo/config.yaml:"
echo ""
echo "  tts:"
echo "    engine: f5tts_clone"
echo "    f5tts:"
echo "      ckpt_file: $CKPT"
echo "      vocab_file: $VOCAB"
echo "      device: cpu            # mps may have known macOS regressions"
echo ""
echo "Record a fresh reference (≤15s, clear speech):"
echo "  saymo record-voice -d 12"
echo ""
echo "Then verify with:  saymo test-tts \"Доброе утро коллеги.\""
